# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-08 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('summary', models.CharField(blank=True, max_length=200, verbose_name='Resumen')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicacion')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado?')),
                ('img', models.ImageField(blank=True, upload_to='post_images', verbose_name='Imagen del post')),
                ('start_date', models.DateTimeField(blank=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='Fecha final')),
                ('location', models.TextField(verbose_name='Ubicacion')),
                ('gmap_link', models.URLField(blank=True, default='', help_text='Link externo de Googlemaps del evento', verbose_name='Link a Google Maps')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.Member')),
            ],
            options={
                'verbose_name': 'Eventos',
            },
        ),
    ]
