# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-06 06:00
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0002_cell_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='content',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, max_length=2000, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique_with=('name',)),
        ),
    ]
