# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-14 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.image
import fontawesome.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Titulo')),
                ('content', models.CharField(blank=True, max_length=150, verbose_name='Contenido')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BannerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.Page')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='widgets.BannerGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Principle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Titulo')),
                ('content', models.CharField(blank=True, max_length=150, verbose_name='Contenido')),
                ('icon', fontawesome.fields.IconField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='PrincipleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.Page')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='widgets.PrincipleGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.Page')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='widgets.Slider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Titulo')),
                ('content', models.CharField(blank=True, max_length=150, verbose_name='Contenido')),
                ('img', filer.fields.image.FilerImageField(blank=True, help_text='Tamaño sugerido: 1024x764', null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image', verbose_name='Imagen')),
                ('slider', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='widgets.Slider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='principle',
            name='principles',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='widgets.PrincipleGroup'),
        ),
        migrations.AddField(
            model_name='banner',
            name='banners',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='widgets.BannerGroup'),
        ),
        migrations.AddField(
            model_name='banner',
            name='img',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Tamaño sugerido: 1024x764', null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image', verbose_name='Imagen'),
        ),
    ]
