# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-11 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0004_auto_20170811_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homebannerextension',
            name='followus_banner',
        ),
        migrations.RemoveField(
            model_name='homebannerextension',
            name='followus_banner_content',
        ),
        migrations.RemoveField(
            model_name='homebannerextension',
            name='followus_banner_title',
        ),
        migrations.RemoveField(
            model_name='homebannerextension',
            name='sermon_banner',
        ),
        migrations.RemoveField(
            model_name='homebannerextension',
            name='sermon_banner_content',
        ),
        migrations.RemoveField(
            model_name='homebannerextension',
            name='sermon_banner_title',
        ),
        migrations.RemoveField(
            model_name='homebannerextension',
            name='thought_banner',
        ),
        migrations.RemoveField(
            model_name='homebannerextension',
            name='thought_banner_content',
        ),
        migrations.RemoveField(
            model_name='homebannerextension',
            name='thought_banner_title',
        ),
        migrations.AddField(
            model_name='homebannerextension',
            name='banners',
            field=models.ManyToManyField(blank=True, to='widgets.BannerExtension'),
        ),
        migrations.AlterField(
            model_name='principleextension',
            name='content',
            field=models.CharField(blank=True, max_length=150, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='principleextension',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Titulo'),
        ),
    ]
