# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-11 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0005_auto_20170811_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderextension',
            name='slider',
        ),
        migrations.AddField(
            model_name='sliderimageextension',
            name='slider',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='widgets.SliderExtension'),
            preserve_default=False,
        ),
    ]
