# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-11 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0006_auto_20170811_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderimageextension',
            name='slider',
        ),
        migrations.AddField(
            model_name='sliderextension',
            name='slides',
            field=models.ManyToManyField(blank=True, to='widgets.SliderImageExtension'),
        ),
    ]
