# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-11 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import fontawesome.fields


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0008_auto_20170811_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Titulo')),
                ('content', models.CharField(blank=True, max_length=150, verbose_name='Contenido')),
                ('icon', fontawesome.fields.IconField(blank=True, max_length=60)),
            ],
        ),
        migrations.RenameModel(
            old_name='BannerExtension',
            new_name='Banner',
        ),
        migrations.RenameModel(
            old_name='HomeBannerExtension',
            new_name='HomeBanner',
        ),
        migrations.RenameModel(
            old_name='PrincipleGroupExtension',
            new_name='PrincipleGroup',
        ),
        migrations.RenameModel(
            old_name='SliderExtension',
            new_name='Slider',
        ),
        migrations.RenameModel(
            old_name='SliderImageExtension',
            new_name='SliderImage',
        ),
        migrations.RemoveField(
            model_name='principleextension',
            name='extended_object',
        ),
        migrations.RemoveField(
            model_name='principleextension',
            name='public_extension',
        ),
        migrations.AlterField(
            model_name='principlegroup',
            name='principles',
            field=models.ManyToManyField(blank=True, to='widgets.Principle'),
        ),
        migrations.DeleteModel(
            name='PrincipleExtension',
        ),
    ]
