# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-11 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0009_auto_20170811_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='slides',
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='slider',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='widgets.Slider'),
            preserve_default=False,
        ),
    ]
