# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-11 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('widgets', '0010_auto_20170811_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.Page')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='widgets.BannerGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='homebanner',
            name='banners',
        ),
        migrations.RemoveField(
            model_name='homebanner',
            name='extended_object',
        ),
        migrations.RemoveField(
            model_name='homebanner',
            name='public_extension',
        ),
        migrations.RemoveField(
            model_name='principlegroup',
            name='principles',
        ),
        migrations.AddField(
            model_name='principle',
            name='principles',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='widgets.PrincipleGroup'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HomeBanner',
        ),
        migrations.AddField(
            model_name='banner',
            name='banners',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='widgets.BannerGroup'),
            preserve_default=False,
        ),
    ]
