# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('summary', models.CharField(blank=True, max_length=200, verbose_name='Resumen')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicacion')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado?')),
                ('img', models.ImageField(blank=True, upload_to='post_images', verbose_name='Imagen del post')),
                ('content', models.TextField(blank=True, max_length=1200, verbose_name='Contenido')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sermons.Author')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='sermons.Tag')),
            ],
            options={
                'verbose_name': 'Reflexiones',
            },
        ),
    ]
