# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 05:01
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0003_auto_20170808_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='img',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Tamaño sugerido: 1024x765', null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image', verbose_name='Imagen del post'),
        ),
    ]
