# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0004_auto_20170809_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creacion'),
            preserve_default=False,
        ),
    ]
