# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-14 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.image
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('sermons', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('summary', models.CharField(blank=True, max_length=200, verbose_name='Resumen')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicacion')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado?')),
                ('date_created', models.DateTimeField(verbose_name='Fecha de creacion')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('start_date', models.DateTimeField(blank=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='Fecha final')),
                ('location', models.TextField(blank=True, verbose_name='Ubicacion')),
                ('gmap_link', models.URLField(blank=True, default='', help_text='Link externo de Googlemaps del evento', verbose_name='Link a Google Maps')),
                ('img', filer.fields.image.FilerImageField(blank=True, help_text='Tamaño sugerido: 1024x765', null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image', verbose_name='Imagen del post')),
                ('tags', models.ManyToManyField(to='sermons.Tag')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-start_date'],
            },
        ),
    ]
