# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 04:53
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='name', unique_with=('name',)),
            preserve_default=False,
        ),
    ]
