# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-08 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_created',
        ),
        migrations.AddField(
            model_name='event',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='event',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, verbose_name='Fecha final'),
        ),
        migrations.AlterField(
            model_name='event',
            name='gmap_link',
            field=models.URLField(blank=True, default='', help_text='Link externo de Googlemaps del evento', verbose_name='Link a Google Maps'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.TextField(verbose_name='Ubicacion'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(blank=True, verbose_name='Fecha de inicio'),
        ),
    ]
