# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-12 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.TextField(blank=True, verbose_name='Ubicacion'),
        ),
    ]
