# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-06 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.file
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCDSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=100, verbose_name='Correo electrónico')),
                ('cellphone', models.CharField(blank=True, max_length=15, null=True)),
                ('voucher', filer.fields.file.FilerFileField(blank=True, help_text='Tamaño sugerido: 1024x765', null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File', verbose_name='voucher')),
            ],
            options={
                'verbose_name': 'Subscriptor',
                'verbose_name_plural': 'Subscriptors',
            },
        ),
    ]
