# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-08 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20170808_0207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Red social', 'verbose_name_plural': 'Redes sociales'},
        ),
    ]
