# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 04:23
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('membership', '0003_auto_20170808_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='img',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Tamaño sugerido: 50x50', null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image', verbose_name='imagen de perfil'),
        ),
    ]
