# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-08 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0002_auto_20170808_0158'),
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='author',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='date_created',
        ),
        migrations.AddField(
            model_name='sermon',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.Member'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='tags',
            field=models.ManyToManyField(blank=True, to='sermons.Tag'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
