# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-08 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0002_auto_20170808_0158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sermon',
            options={'verbose_name': 'Sermon', 'verbose_name_plural': 'Sermones'},
        ),
    ]
