# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0005_sermon_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='date_created',
            field=models.DateTimeField(verbose_name='Fecha de creacion'),
        ),
    ]
